name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: 'illuminator-optimai'  # Replace with your actual Google Cloud project ID
  REGION: 'europe-southwest1'  # Replace with your preferred region
  SERVICE: 'python-executor'  # Replace with your Cloud Run service name

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/389448867152/locations/global/workloadIdentityPools/github/providers/executor'  # Replace with your actual Workload Identity Provider
          project_id: '${{ env.PROJECT_ID }}'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'
          project_id: '${{ env.PROJECT_ID }}'

      - name: 'Show deployment output'
        run: echo ${{ steps.deploy.outputs.url }}
